version: '3.1'

services:
  db:
    image: mariadb:10.6.7
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MARIADB_USER: cyberyami
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80